package jetbrains.mps.tutorial.calculator.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.BaseStructureAspectDescriptor;
import jetbrains.mps.smodel.runtime.ConceptDescriptor;
import java.util.Collection;
import java.util.Arrays;
import org.jetbrains.annotations.Nullable;
import jetbrains.mps.smodel.adapter.ids.SConceptId;
import org.jetbrains.mps.openapi.language.SAbstractConcept;
import jetbrains.mps.smodel.runtime.impl.ConceptDescriptorBuilder2;

public class StructureAspectDescriptor extends BaseStructureAspectDescriptor {
  /*package*/ final ConceptDescriptor myConceptCalculator = createDescriptorForCalculator();
  /*package*/ final ConceptDescriptor myConceptInputField = createDescriptorForInputField();
  /*package*/ final ConceptDescriptor myConceptInputFieldReference = createDescriptorForInputFieldReference();
  /*package*/ final ConceptDescriptor myConceptOutputField = createDescriptorForOutputField();
  private final LanguageConceptSwitch myIndexSwitch;

  public StructureAspectDescriptor() {
    myIndexSwitch = new LanguageConceptSwitch();
  }


  @Override
  public void reportDependencies(jetbrains.mps.smodel.runtime.StructureAspectDescriptor.Dependencies deps) {
    deps.extendedLanguage(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, "jetbrains.mps.lang.core");
    deps.extendedLanguage(0xf3061a5392264cc5L, 0xa443f952ceaf5816L, "jetbrains.mps.baseLanguage");
    deps.aggregatedLanguage(0xf3061a5392264cc5L, 0xa443f952ceaf5816L, "jetbrains.mps.baseLanguage");
  }

  @Override
  public Collection<ConceptDescriptor> getDescriptors() {
    return Arrays.asList(myConceptCalculator, myConceptInputField, myConceptInputFieldReference, myConceptOutputField);
  }

  @Override
  @Nullable
  public ConceptDescriptor getDescriptor(SConceptId id) {
    switch (myIndexSwitch.index(id)) {
      case LanguageConceptSwitch.Calculator:
        return myConceptCalculator;
      case LanguageConceptSwitch.InputField:
        return myConceptInputField;
      case LanguageConceptSwitch.InputFieldReference:
        return myConceptInputFieldReference;
      case LanguageConceptSwitch.OutputField:
        return myConceptOutputField;
      default:
        return null;
    }
  }


  /*package*/ int internalIndex(SAbstractConcept c) {
    return myIndexSwitch.index(c);
  }

  private static ConceptDescriptor createDescriptorForCalculator() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("jetbrains.mps.tutorial.calculator", "Calculator", 0xaa123d6efbb1411fL, 0xa37772f5117888d8L, 0x641798472a626c8cL);
    b.class_(false, false, true);
    b.parent(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L);
    b.origin("r:aabbec82-996c-4f76-a03f-37478e9e8704(jetbrains.mps.tutorial.calculator.structure)/7212400759678332044");
    b.version(3);
    b.aggregate("inputField", 0x641798472a65016eL).target(0xaa123d6efbb1411fL, 0xa37772f5117888d8L, 0x641798472a650151L).optional(true).ordered(true).multiple(true).origin("7212400759678501230").done();
    b.aggregate("outputField", 0x641798472a65666cL).target(0xaa123d6efbb1411fL, 0xa37772f5117888d8L, 0x641798472a656660L).optional(true).ordered(true).multiple(true).origin("7212400759678527084").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForInputField() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("jetbrains.mps.tutorial.calculator", "InputField", 0xaa123d6efbb1411fL, 0xa37772f5117888d8L, 0x641798472a650151L);
    b.class_(false, false, false);
    b.parent(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L);
    b.origin("r:aabbec82-996c-4f76-a03f-37478e9e8704(jetbrains.mps.tutorial.calculator.structure)/7212400759678501201");
    b.version(3);
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForInputFieldReference() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("jetbrains.mps.tutorial.calculator", "InputFieldReference", 0xaa123d6efbb1411fL, 0xa37772f5117888d8L, 0x641798472a65df52L);
    b.class_(false, false, false);
    // extends: jetbrains.mps.baseLanguage.structure.Expression
    b.super_(0xf3061a5392264cc5L, 0xa443f952ceaf5816L, 0xf8c37f506fL);
    b.origin("r:aabbec82-996c-4f76-a03f-37478e9e8704(jetbrains.mps.tutorial.calculator.structure)/7212400759678558034");
    b.version(3);
    b.associate("field", 0x641798472a65df62L).target(0xaa123d6efbb1411fL, 0xa37772f5117888d8L, 0x641798472a650151L).optional(false).origin("7212400759678558050").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForOutputField() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("jetbrains.mps.tutorial.calculator", "OutputField", 0xaa123d6efbb1411fL, 0xa37772f5117888d8L, 0x641798472a656660L);
    b.class_(false, false, false);
    b.parent(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L);
    b.origin("r:aabbec82-996c-4f76-a03f-37478e9e8704(jetbrains.mps.tutorial.calculator.structure)/7212400759678527072");
    b.version(3);
    b.aggregate("expression", 0x641798472a65df48L).target(0xf3061a5392264cc5L, 0xa443f952ceaf5816L, 0xf8c37f506fL).optional(false).ordered(true).multiple(false).origin("7212400759678558024").done();
    return b.create();
  }
}
